<?php

/**
 * @file
 * Contains h5p_analytics.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function h5p_analytics_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the h5p_analytics module.
    case 'help.page.h5p_analytics':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('H5P xAPI LRS integration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 */
function h5p_analytics_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'h5p_analytics/behaviour';
  $attachments['#attached']['drupalSettings']['H5PAnalytics'] = [
    'endpointUrl' => Url::fromRoute('h5p_analytics.lrs_controller_xapi')->toString(),
  ];
}

/**
 * Implements hook_h5p_scripts_alter().
 * Is used solely for external (embedded) pages, those are fully unrelated to
 * the rest of Drupal JS logic
 */
function h5p_analytics_h5p_scripts_alter(&$scripts, $libraries, $mode) {
  if ($mode === 'external') {
    $scripts[] = (object) [
      'path' => drupal_get_path('module', 'h5p_analytics') . '/js/external.js',
      'version' => '1.x',
    ];
  }
}

/**
 * Implements hook_cron().
 */
function h5p_analytics_cron() {
  \Drupal::service('h5p_analytics.lrs')->processStatementsCron();
}
